<a href="https://colab.research.google.com/github/Richaweb/DS/blob/main/Recommendation_system_osean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Collaborative Analysis Using KNN

In [ ]:
#pip install scikit -learn

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import NearestNeighbors
from scipy.sparse import csr_matrix
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
anime = pd.read_csv('/content/anime.csv')
rating = pd.read_csv('/content/rating.csv')

In [ ]:
anime.shape

(12294, 7)

In [ ]:
anime.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [ ]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [ ]:
anime.describe(include='all')

,anime_id,name,genre,type,episodes,rating,members
count,12294.000000,12294,12232,12269,12294,12064.000000,1.229400e+04
unique,NaN,12292,3264,6,187,NaN,NaN
top,NaN,Saru Kani Gassen,Hentai,TV,1,NaN,NaN
freq,NaN,2,823,3787,5677,NaN,NaN
mean,14058.221653,NaN,NaN,NaN,NaN,6.473902,1.807134e+04
std,11455.294701,NaN,NaN,NaN,NaN,1.026746,5.482068e+04
min,1.000000,NaN,NaN,NaN,NaN,1.670000,5.000000e+00
25%,3484.250000,NaN,NaN,NaN,NaN,5.880000,2.250000e+02
50%,10260.500000,NaN,NaN,NaN,NaN,6.570000,1.550000e+03
75%,24794.500000,NaN,NaN,NaN,NaN,7.180000,9.437000e+03
max,34527.000000,NaN,NaN,NaN,NaN,10.000000,1.013917e+06

In [ ]:
rating.shape

(7813737, 3)

In [ ]:
rating.describe()

            user_id      anime_id        rating
count  7.813737e+06  7.813737e+06  7.813737e+06
mean   3.672796e+04  8.909072e+03  6.144030e+00
std    2.099795e+04  8.883950e+03  3.727800e+00
min    1.000000e+00  1.000000e+00 -1.000000e+00
25%    1.897400e+04  1.240000e+03  6.000000e+00
50%    3.679100e+04  6.213000e+03  7.000000e+00
75%    5.475700e+04  1.409300e+04  9.000000e+00
max    7.351600e+04  3.451900e+04  1.000000e+01

In [ ]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7813737 entries, 0 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 178.8 MB

In [ ]:
rating = rating[rating['rating'] != -1]
rating.shape

(6337241, 3)

In [ ]:
#check for null value in anime dataset.

In [ ]:
anime.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [ ]:
#handle null values
anime = anime.drop(list(anime.loc[anime['rating'].isnull()==True].index),axis=0)
anime = anime.fillna('Unknown')
anime = anime.reset_index(drop=True)

In [ ]:
anime.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [ ]:
anime['genre'].unique()

array(['Drama, Romance, School, Supernatural',
       'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen',
       'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
       ..., 'Action, Comedy, Hentai, Romance, Supernatural',
       'Hentai, Sports', 'Hentai, Slice of Life'], dtype=object)

In [ ]:
anime['type'].unique()

array(['Movie', 'TV', 'OVA', 'Special', 'Music', 'ONA'], dtype=object)

#check for duplicate users

In [ ]:
sampled_users=rating['user_id'].drop_duplicates().sample(n=10000,random_state=40).values
filter_rating=rating[rating['user_id'].isin(sampled_users)]

In [ ]:
user_index ={user: index for index, user in enumerate(filter_rating['user_id'].unique())}
anime_index ={anime: index for index, anime in enumerate(filter_rating['anime_id'].unique())}


rows = filter_rating['user_id'].map(user_index).astype(np.int64).values
col = filter_rating['user_id'].map(user_index).astype(np.int64).values
values = filter_rating['rating'].astype(np.float64).values

In [ ]:
sparse_matrix = csr_matrix((values, (rows, col)))

#Model Training

In [ ]:
knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=15)
knn.fit(sparse_matrix.tocsr())

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=15)

In [ ]:
#random users lists
random_user = np.random.randint(0, sparse_matrix.shape[0])
random_user_vector = sparse_matrix.getrow(random_user).toarray().reshape(1,-1)

In [ ]:
#similar users
distances, indices = knn.kneighbors(random_user_vector, n_neighbors=15)
similar_users = indices[0]

#Get Random Users

In [ ]:
random_user_id = list(user_index.keys())[random_user]
user_anime = set(filter_rating[filter_rating['user_id'] == random_user_id]['anime_id'])

In [ ]:
recommendations_anime = set()

for user in similar_users:
    user_id = list(user_index.keys())[user]
    recommendations_anime.update(filter_rating[filter_rating['user_id'] == user_id]['anime_id'].values)


recommendations_anime.difference_update(user_anime)

In [ ]:
recommendations_anime_names = anime[anime['anime_id'].isin(recommendations_anime)]['name']

In [ ]:
print('Anime Recommendation:')
for i, anime_name in enumerate(recommendations_anime_names,1):
  print(f'{i}. {anime_name}')

Anime Recommendation:
1. Fullmetal Alchemist: Brotherhood
2. Steins;Gate
3. Gintama&#039;
4. Gintama&#039;: Enchousen
5. Clannad: After Story
6. Gintama
7. Code Geass: Hangyaku no Lelouch R2
8. Sen to Chihiro no Kamikakushi
9. Ookami Kodomo no Ame to Yuki
10. Code Geass: Hangyaku no Lelouch
11. Hajime no Ippo
12. Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen
13. Cowboy Bebop
14. One Punch Man
15. Mononoke Hime
16. Suzumiya Haruhi no Shoushitsu
17. Monogatari Series: Second Season
18. Mushishi
19. Great Teacher Onizuka
20. Hajime no Ippo: New Challenger
21. Howl no Ugoku Shiro
22. Fate/Zero 2nd Season
23. Monster
24. Bakuman. 3rd Season
25. Death Note
26. Hajime no Ippo: Rising
27. Kara no Kyoukai 5: Mujun Rasen
28. Natsume Yuujinchou San
29. Boku dake ga Inai Machi
30. Aria The Origination
31. Tengen Toppa Gurren Lagann Movie: Lagann-hen
32. Zoku Natsume Yuujinchou
33. Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.
34. Steins;Gate Movie: Fuka Ryouiki no Déjà vu
35. Hotarubi no Mori e
36. Gintama Movie: Shinyaku Benizakura-hen
37. Hellsing Ultimate
38. Kiseijuu: Sei no Kakuritsu
39. Hotaru no Haka
40. Ghost in the Shell: Stand Alone Complex 2nd GIG
41. Kara no Kyoukai 7: Satsujin Kousatsu (Kou)
42. Slam Dunk
43. Usagi Drop
44. Nana
45. Baccano!
46. Shingeki no Kyojin
47. Bakuman. 2nd Season
48. Evangelion: 2.0 You Can (Not) Advance
49. Shinsekai yori
50. Chihayafuru 2
51. Mahou Shoujo Madoka★Magica
52. Nichijou
53. Psycho-Pass
54. Samurai Champloo
55. Katanagatari
56. Hunter x Hunter
57. Sakamichi no Apollon
58. Tonari no Totoro
59. Ghost in the Shell: Stand Alone Complex
60. No Game No Life
61. Yuu☆Yuu☆Hakusho
62. Kino no Tabi: The Beautiful World
63. Nodame Cantabile
64. Ookami to Koushinryou II
65. Steins;Gate: Oukoubakko no Poriomania
66. Kemono no Souja Erin
67. Neon Genesis Evangelion: The End of Evangelion
68. Toradora!
69. Toki wo Kakeru Shoujo
70. Rurouni Kenshin: Meiji Kenkaku Romantan
71. Stranger: Mukou Hadan
72. Nanatsu no Taizai
73. Natsume Yuujinchou
74. Higurashi no Naku Koro ni Kai
75. Hunter x Hunter OVA
76. Hunter x Hunter: Greed Island Final
77. One Outs
78. Beck
79. Berserk
80. Cowboy Bebop: Tengoku no Tobira
81. NHK ni Youkoso!
82. Rose of Versailles
83. Sakurasou no Pet na Kanojo
84. Angel Beats!
85. Bakemonogatari
86. Hajime no Ippo: Champion Road
87. Ouran Koukou Host Club
88. Nodame Cantabile Finale
89. Gintama: Shiroyasha Koutan
90. Katekyo Hitman Reborn!
91. Ookami to Koushinryou
92. Gin no Saji 2nd Season
93. SKET Dance
94. Bakuman.
95. Danshi Koukousei no Nichijou
96. Ghost in the Shell
97. K-On! Movie
98. Steins;Gate: Kyoukaimenjou no Missing Link - Divide By Zero
99. xxxHOLiC Kei
100. Death Parade
101. Fullmetal Alchemist
102. Hunter x Hunter: Greed Island
103. Redline
104. Chihayafuru
105. Dragon Ball Z
106. Neon Genesis Evangelion
107. Tokyo Godfathers
108. Trigun
109. Sekaiichi Hatsukoi 2
110. Aria The Natural
111. Black Lagoon: The Second Barrage
112. Clannad
113. Kami nomi zo Shiru Sekai: Megami-hen
114. Summer Wars
115. Baccano! Specials
116. Hajime no Ippo: Mashiba vs. Kimura
117. Skip Beat!
118. Majo no Takkyuubin
119. Nodame Cantabile: Paris-hen
120. Tsumiki no Ie
121. Eve no Jikan
122. Eve no Jikan (Movie)
123. Kaichou wa Maid-sama!
124. Saint Seiya: Meiou Hades Juuni Kyuu-hen
125. Darker than Black: Kuro no Keiyakusha
126. Non Non Biyori Repeat
127. Shijou Saikyou no Deshi Kenichi
128. Gekkan Shoujo Nozaki-kun
129. Junjou Romantica 2
130. Kuragehime
131. Magi: The Labyrinth of Magic
132. Mobile Suit Gundam 00
133. Saint Seiya: The Lost Canvas - Meiou Shinwa
134. Seirei no Moribito
135. Gosick
136. Hajime no Ippo: Boxer no Kobushi
137. Kill la Kill
138. Lovely★Complex
139. Perfect Blue
140. Tengen Toppa Gurren Lagann Movie: Gurren-hen
141. Evangelion: 1.0 You Are (Not) Alone
142. Full Metal Panic? Fumoffu
143. Kara no Kyoukai 3: Tsuukaku Zanryuu
144. Nisemonogatari
145. Ansatsu Kyoushitsu (TV)
146. D.Gray-man
147. Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai. Movie
148. Eureka Seven
149. Kimi ni Todoke
150. Kokoro Connect: Michi Random
151. Tokyo Magnitude 8.0
152. Cardcaptor Sakura
153. ef: A Tale of Melodies.
154. Gin no Saji
155. Hachimitsu to Clover
156. Sekaiichi Hatsukoi OVA
157. Black Lagoon
158. Final Fantasy VII: Advent Children Complete
159. Higurashi no Naku Koro ni
160. Interstella5555: The 5tory of The 5ecret 5tar 5ystem
161. Kanon (2006)
162. Kimi ni Todoke 2nd Season
163. xxxHOLiC Shunmuki
164. Aria The Origination: Sono Choppiri Himitsu no Basho ni...
165. Dragon Ball
166. Juuni Kokuki
167. Phantom: Requiem for the Phantom
168. Toaru Kagaku no Railgun S
169. Akira
170. Black Lagoon: Roberta&#039;s Blood Trail
171. Paprika
172. Prince of Tennis: The National Tournament Finals
173. School Rumble Ni Gakki
174. Sekaiichi Hatsukoi
175. Akagami no Shirayuki-hime 2nd Season
176. Clannad: Mou Hitotsu no Sekai, Tomoyo-hen
177. K-On!!
178. Slayers Next
179. Aria The OVA: Arietta
180. Gintama: Nanigoto mo Saiyo ga Kanjin nano de Tasho Senobisuru Kurai ga Choudoyoi
181. Kamisama Hajimemashita
182. ef: A Tale of Memories.
183. Ghost in the Shell 2.0
184. Kami nomi zo Shiru Sekai II
185. Yahari Ore no Seishun Love Comedy wa Machigatteiru.
186. Fullmetal Alchemist: Brotherhood Specials
187. Kimi to Boku. 2
188. Ore Monogatari!!
189. xxxHOLiC
190. Byousoku 5 Centimeter
191. Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou-hen
192. Darker than Black: Kuro no Keiyakusha Gaiden
193. Hybrid Child
194. Isekai no Seikishi Monogatari
195. Kobato.
196. Prince of Tennis: The National Tournament
197. Prince of Tennis: The National Tournament Semifinals
198. Eyeshield 21
199. Jigoku Shoujo Futakomori
200. Junjou Romantica
201. Mawaru Penguindrum
202. Soul Eater
203. Trigun: Badlands Rumble
204. Haibane Renmei
205. Mirai Nikki (TV)
206. Tokyo Ghoul
207. Usagi Drop Specials
208. Azumanga Daioh
209. FLCL
210. Full Metal Panic! The Second Raid
211. Kuroshitsuji
212. Nekomonogatari: Kuro
213. School Rumble
214. Suzumiya Haruhi no Yuuutsu
215. Golden Boy
216. Kara no Kyoukai 4: Garan no Dou
217. Non Non Biyori
218. Yakitate!! Japan
219. Beelzebub
220. Jormungand: Perfect Order
221. Prince of Tennis
222. xxxHOLiC Movie: Manatsu no Yoru no Yume
223. Ergo Proxy
224. Hanasaku Iroha
225. Hataraku Maou-sama!
226. Higashi no Eden
227. Kono Subarashii Sekai ni Shukufuku wo!
228. Mobile Suit Zeta Gundam
229. Saint Seiya
230. Sayonara Zetsubou Sensei
231. Seto no Hanayome OVA
232. Clannad: After Story - Mou Hitotsu no Sekai, Kyou-hen
233. Kara no Kyoukai 2: Satsujin Kousatsu (Zen)
234. Macross F
235. Carnival Phantasm
236. Kokoro Connect
237. Zan Sayonara Zetsubou Sensei
238. City Hunter
239. Break Blade 4: Sanka no Chi
240. Hanasaku Iroha: Home Sweet Home
241. Hokuto no Ken
242. Serial Experiments Lain
243. Shiki
244. Baka to Test to Shoukanjuu Ni!
245. Working&#039;!!
246. Gate: Jieitai Kanochi nite, Kaku Tatakaeri
247. Gate: Jieitai Kanochi nite, Kaku Tatakaeri 2nd Season
248. Ghost Hunt
249. Gungrave
250. Ookami to Koushinryou II: Ookami to Kohakuiro no Yuuutsu
251. Saint Seiya: Meiou Hades Meikai-hen
252. Break Blade 5: Shisen no Hate
253. Jormungand
254. Bleach
255. Chuunibyou demo Koi ga Shitai!
256. Dragon Ball Kai
257. Hetalia World Series
258. Kami nomi zo Shiru Sekai
259. Seto no Hanayome
260. Tasogare Otome x Amnesia
261. Vampire Hunter D (2000)
262. Break Blade 3: Kyoujin no Ato
263. Danshi Koukousei no Nichijou Specials
264. Final Fantasy VII: Advent Children
265. Last Exile
266. Akagami no Shirayuki-hime
267. Ghost in the Shell 2: Innocence
268. Mobile Suit Gundam Seed
269. Nodame Cantabile Finale Special
270. Slayers Try
271. Wolf&#039;s Rain
272. Ao no Exorcist
273. Claymore
274. Golden Time
275. Hayate no Gotoku!!
276. Jinrui wa Suitai Shimashita
277. Lucky☆Star: Original na Visual to Animation
278. Pandora Hearts
279. Rurouni Kenshin DVD-BOX Special Ending
280. Charlotte
281. Kino no Tabi: Nanika wo Suru Tame ni - Life Goes On.
282. Michiko to Hatchin
283. Ao Haru Ride
284. Digimon Adventure
285. InuYasha
286. InuYasha: Tenka Hadou no Ken
287. K-On!!: Keikaku!
288. Seitokai Yakuindomo OVA
289. Yamato Nadeshiko Shichihenge♥
290. Another
291. Binbougami ga!
292. K-On!: Live House!
293. Kyou kara Maou!
294. The Last: Naruto the Movie
295. The Law of Ueki
296. High School DxD New
297. K-On!
298. Kino no Tabi: The Beautiful World - Byouki no Kuni - For You
299. Lucky☆Star
300. Mobile Suit Gundam Wing
301. Ranma ½
302. Slayers
303. Sora no Otoshimono: Tokeijikake no Angeloid
304. Toaru Kagaku no Railgun
305. Break Blade 2: Ketsubetsu no Michi
306. Genshiken 2
307. Sora no Otoshimono: Forte
308. Arakawa Under the Bridge x Bridge
309. Elfen Lied
310. Kami nomi zo Shiru Sekai: Tenri-hen
311. Kimi to Boku.
312. Mahou Sensei Negima! Mou Hitotsu no Sekai
313. Mondaiji-tachi ga Isekai kara Kuru Sou Desu yo?
314. One Punch Man: Road to Hero
315. Romeo x Juliet
316. School Rumble Ichi Gakki Hoshuu
317. Akame ga Kill!
318. AKB0048: Next Stage
319. Death Note Rewrite
320. Hakuouki Sekkaroku
321. Memories
322. Seitokai Yakuindomo*
323. Toaru Majutsu no Index II
324. Baka to Test to Shoukanjuu
325. Ichigo Mashimaro OVA
326. Mobile Police Patlabor 2: The Movie
327. Rozen Maiden: Ouvertüre
328. Shaman King
329. Sword Art Online
330. Tetsuwan Birdy Decode:02
331. Bokurano
332. Bounen no Xamdou
333. Dragon Ball Z Special 2: Zetsubou e no Hankou!! Nokosareta Chousenshi - Gohan to Trunks
334. Kill la Kill Special
335. Mitsudomoe Zouryouchuu!
336. Saint Seiya: Meiou Hades Elysion-hen
337. To LOVE-Ru Darkness
338. To LOVE-Ru Darkness OVA
339. Working!!
340. Full Metal Panic!
341. Guilty Crown
342. Hoshi wo Ou Kodomo
343. Jigoku Shoujo Mitsuganae
344. Kara no Kyoukai 1: Fukan Fuukei
345. Minami-ke
346. Naruto
347. Baka to Test to Shoukanjuu: Matsuri
348. Blood+
349. Chrno Crusade
350. Fruits Basket
351. Hourou Musuko
352. Soredemo Sekai wa Utsukushii
353. Tenkuu no Escaflowne
354. Angel Beats! Specials
355. Aria The Animation
356. Break Blade 1: Kakusei no Toki
357. Denpa-teki na Kanojo
358. Dragon Quest: Dai no Daibouken
359. Ichigo Mashimaro Encore
360. Jigoku Shoujo
361. Panty &amp; Stocking with Garterbelt
362. Servant x Service
363. Shakugan no Shana II (Second)
364. Full Metal Panic! The Second Raid: Wari to Hima na Sentaichou no Ichinichi
365. Ga-Rei: Zero
366. Higashi no Eden Movie II: Paradise Lost
367. Kore wa Zombie Desu ka? of the Dead
368. Minami-ke Tadaima
369. R.O.D OVA
370. Rozen Maiden: Träumend
371. Special A
372. Tenchi Muyou! Ryououki 2nd Season
373. Texhnolyze
374. Utawarerumono
375. Black Jack 21
376. Ichigo Mashimaro
377. Tenchi Muyou! Ryououki
378. Tonari no Kaibutsu-kun
379. Zero no Tsukaima F
380. Genshiken
381. Hakuouki Hekketsuroku
382. Hetalia Axis Powers
383. Itazura na Kiss
384. Mahouka Koukou no Rettousei
385. Majin Tantei Nougami Neuro
386. No.6
387. Senjou no Valkyria
388. Tegamibachi
389. Bleach Movie 4: Jigoku-hen
390. Dragon Ball Z Special 1: Tatta Hitori no Saishuu Kessen
391. Hayate no Gotoku!
392. InuYasha: Kagami no Naka no Mugenjo
393. Kino no Tabi: The Beautiful World - Tou no Kuni
394. The iDOLM@STER
395. Bishoujo Senshi Sailor Moon R
396. Black Jack (TV)
397. Fullmetal Alchemist: The Conqueror of Shamballa
398. Genshiken OVA
399. Hal
400. Higashi no Eden Movie I: The King of Eden
401. Shakugan no Shana
402. GetBackers
403. Mitsudomoe
404. Shakugan no Shana III (Final)
405. Zero no Tsukaima: Futatsuki no Kishi
406. Dragon Ball Z Movie 12: Fukkatsu no Fusion!! Gokuu to Vegeta
407. Kara no Kyoukai 6: Boukyaku Rokuon
408. Mobile Police Patlabor: On Television
409. Aa! Megami-sama!: Tatakau Tsubasa
410. Arakawa Under the Bridge
411. Bishoujo Senshi Sailor Moon
412. Evangelion: 3.0 You Can (Not) Redo
413. Fullmetal Alchemist: Brotherhood - 4-Koma Theater
414. Gensoumaden Saiyuuki
415. Seitokai Yakuindomo
416. Sukitte Ii na yo.
417. Toaru Majutsu no Index: Endymion no Kiseki
418. Ano Natsu de Matteru
419. Boku wa Tomodachi ga Sukunai Next
420. High School DxD
421. Isshuukan Friends.
422. Kamisama no Memochou
423. Love Live! School Idol Project
424. Oda Nobuna no Yabou
425. Strike Witches Movie
426. Yuru Yuri
427. Aa! Megami-sama!: Sorezore no Tsubasa
428. Air Gear
429. Hanbun no Tsuki ga Noboru Sora
430. Inu x Boku SS
431. InuYasha: Toki wo Koeru Omoi
432. Kiniro no Corda: Primo Passo
433. Kuroshitsuji Special
434. Love Stage!!
435. Nodame Cantabile OVA 2
436. Saenai Heroine no Sodatekata
437. Toaru Majutsu no Index
438. Tonari no Seki-kun
439. Basilisk: Kouga Ninpou Chou
440. Btooom!
441. Mahou Sensei Negima! Shiroki Tsubasa Ala Alba
442. Persona 4 the Animation
443. Sora no Otoshimono
444. Juubee Ninpuuchou
445. Kore wa Zombie Desu ka?
446. Bleach Movie 3: Fade to Black - Kimi no Na wo Yobu
447. Girls und Panzer
448. Konjiki no Gash Bell!!
449. Ore no Imouto ga Konnani Kawaii Wake ga Nai Specials
450. Shion no Ou
451. Aa! Megami-sama! Movie
452. Acchi Kocchi (TV)
453. Darker than Black: Kuro no Keiyakusha Special
454. Digimon Tamers
455. Minami-ke Okaeri
456. Non Non Biyori: Okinawa e Ikukoto ni Natta
457. Rurouni Kenshin: Meiji Kenkaku Romantan - Ishinshishi e no Chinkonka
458. Aa! Megami-sama!: Sorezore no Tsubasa Specials
459. Hellsing
460. Kore wa Zombie Desu ka? of the Dead OVA
461. Little Busters!
462. R.O.D the TV
463. Suisei no Gargantia
464. &quot;Bungaku Shoujo&quot; Movie
465. Angel Beats!: Another Epilogue
466. Mardock Scramble: The First Compression
467. Rokka no Yuusha
468. Sora no Otoshimono: Project Pink
469. Suzumiya Haruhi-chan no Yuuutsu
470. Accel World
471. Darker than Black: Ryuusei no Gemini
472. Dragon Ball Z Movie 08: Moetsukiro!! Nessen, Ressen, Chougekisen
473. InuYasha: Guren no Houraijima
474. Naruto: Shippuuden Movie 5 - Blood Prison
475. Shigofumi
476. Shinryaku!? Ika Musume
477. So Ra No Wo To Specials
478. Zero no Tsukaima
479. Aa! Megami-sama! (TV) Specials
480. Amagami SS+ Plus
481. Casshern Sins
482. Digimon Adventure Movie
483. Mobile Police Patlabor: The New Files
484. Motto To LOVE-Ru
485. Sekirei: Pure Engagement
486. Seto no Hanayome OVA Specials
487. Shugo Chara!
488. Bleach Movie 2: The DiamondDust Rebellion - Mou Hitotsu no Hyourinmaru
489. Chuunibyou demo Koi ga Shitai!: Kirameki no... Slapstick Noel
490. Samurai 7
491. Shinryaku! Ika Musume
492. So Ra No Wo To
493. Zero no Tsukaima: Princesses no Rondo
494. Kemonozume
495. Kiniro no Corda: Primo Passo - Hitonatsu no Encore
496. Kyou kara Maou! R
497. Mai-HiME
498. Mikakunin de Shinkoukei
499. Mobile Police Patlabor: The Movie
500. Perfect Day
501. Shinreigari: Ghost Hound
502. Shugo Chara!! Doki
503. Aishiteruze Baby★★
504. Bleach Movie 1: Memories of Nobody
505. Cross Road
506. Fate/stay night
507. Fate/stay night Movie: Unlimited Blade Works
508. Naruto x UT
509. Amagami SS
510. Boku wa Tomodachi ga Sukunai
511. Chobits
512. Chrome Shelled Regios
513. Hakuouki
514. Heppoko Jikken Animation Excel♥Saga
515. Kore wa Zombie Desu ka? OVA
516. Minami-ke Betsubara
517. Nodame Cantabile OVA
518. Rozen Maiden
519. Saki
520. Sengoku Basara
521. Yu☆Gi☆Oh! Duel Monsters
522. Aria The Natural: Sono Futatabi Deaeru Kiseki ni...
523. Carnival Phantasm EX Season
524. Higurashi no Naku Koro ni Rei
525. Tasogare Otome x Amnesia: Taima Otome
526. Tetsuwan Birdy Decode
527. Toaru Kagaku no Railgun: Misaka-san wa Ima Chuumoku no Mato desukara
528. X
529. AKB0048
530. Aoki Hagane no Arpeggio: Ars Nova
531. Blood Lad
532. Danna ga Nani wo Itteiru ka Wakaranai Ken
533. ef: A Tale of Memories. - Recollections
534. Full Metal Panic! The Second Raid Episode 000
535. Gunslinger Girl
536. Himouto! Umaru-chan
537. Kaichou wa Maid-sama!: Omake dayo!
538. Kuroshitsuji II
539. Lodoss-tou Senki
540. Ore no Nounai Sentakushi ga, Gakuen Love Comedy wo Zenryoku de Jama Shiteiru
541. RahXephon
542. Shinryaku!! Ika Musume
543. Sunabouzu
544. True Tears
545. Date A Live
546. Dragon Ball Z Movie 13: Ryuuken Bakuhatsu!! Goku ga Yaraneba Dare ga Yaru
547. Saiyuuki Reload
548. Super Lovers
549. Tenchi Muyou!
550. Toradora!: Bentou no Gokui
551. Vandread: The Second Stage
552. Hiyokoi
553. Hoshi no Koe
554. Kamisama no Inai Nichiyoubi
555. Mayo Chiki!
556. Naruto: Shippuuden Movie 4 - The Lost Tower
557. Sankarea
558. Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai
559. Uta no☆Prince-sama♪ Maji Love 2000%
560. Vampire Knight Guilty
561. Whistle!
562. Black Cat
563. Kanojo to Kanojo no Neko
564. Kowarekake no Orgel (Movie)
565. Kure-nai
566. Outbreak Company
567. Sayonara Zetsubou Sensei Jo: Zetsubou Shoujo Senshuu
568. Scrapped Princess
569. Seitokai no Ichizon
570. Tenchi Muyou! in Love
571. Busou Renkin
572. Mirai Nikki
573. Neon Genesis Evangelion: Death &amp; Rebirth
574. Oban Star-Racers
575. Papa no Iukoto wo Kikinasai!
576. Rurouni Kenshin Special
577. To LOVE-Ru OVA
578. Another: The Other - Inga
579. Fullmetal Alchemist: The Sacred Star of Milos
580. Gangsta.
581. Kaze no Stigma
582. Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsugu Mono
583. Nodame Cantabile Special
584. Tengen Toppa Gurren Lagann Movie: Lagann-hen Special - Viral no Amai Yume
585. Baka to Test to Shoukanjuu Specials
586. Ben-To
587. Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation
588. Danna ga Nani wo Itteiru ka Wakaranai Ken 2 Sure-me
589. Kowarekake no Orgel
590. Love Lab
591. Ore no Imouto ga Konnani Kawaii Wake ga Nai
592. Shakugan no Shana S
593. Tenchi Muyou! Ryououki: Omatsuri Zenjitsu no Yoru!
594. Air
595. Deadman Wonderland
596. GJ-bu
597. Ikoku Meiro no Croisée The Animation
598. Kimikiss Pure Rouge
599. Seitokai no Ichizon Lv.2
600. Shigofumi Special
601. Soredemo Machi wa Mawatteiru
602. Air in Summer
603. Appleseed Saga Ex Machina
604. Asura Cryin&#039; 2
605. Gatchaman Crowds
606. Hakushaku to Yousei
607. Ookami Shoujo to Kuro Ouji
608. Prince of Tennis: The Two Samurai, The First Game
609. Tales of the Abyss
610. Tengen Toppa Gurren Lagann: Mitee Mono wa Miteen da!!
611. Zegapain
612. Afro Samurai: Resurrection
613. Final Fantasy VII: Last Order
614. Handa-kun
615. Hentai Ouji to Warawanai Neko.
616. Highschool of the Dead
617. Mobile Police Patlabor
618. Nekojiru-sou
619. Rec
620. Sabagebu!
621. Shakugan no Shana Movie
622. Speed Grapher
623. Aa! Megami-sama! (TV)
624. Bamboo Blade
625. Fullmetal Alchemist: Premium Collection
626. Hatsukoi Limited
627. Midori no Hibi
628. Papa no Iukoto wo Kikinasai! OVA
629. s.CRY.ed
630. Shikabane Hime: Kuro
631. Beelzebub Specials
632. C: The Money of Soul and Possibility Control
633. Hayate no Gotoku!!: Atsu ga Natsuize - Mizugi-hen!
634. Love Hina Christmas Special: Silent Eve
635. Maoyuu Maou Yuusha
636. Rekka no Honoo
637. Tari Tari
638. Trinity Blood
639. Ao no Exorcist: Kuro no Iede
640. ef: A Tale of Melodies. - Prologue
641. Haiyore! Nyaruko-san W
642. Kannagi
643. Kiba
644. Nagasarete Airantou
645. Naruto: Shippuuden Movie 1
646. Naruto: Shippuuden Movie 2 - Kizuna
647. Ore no Imouto ga Konnani Kawaii Wake ga Nai.
648. Pokemon
649. Rurouni Kenshin: Special Techniques
650. Strike Witches 2
651. Uragiri wa Boku no Namae wo Shitteiru
652. Cheonnyeon-yeowoo Yeowoobi
653. Ikoku Meiro no Croisée Special
654. Kami nomi zo Shiru Sekai: 4-nin to Idol
655. Kimi ni Todoke 2nd Season Specials
656. Onegai☆Teacher: Himitsu na Futari
657. Saint Seiya: Shinku no Shounen Densetsu
658. Zero no Tsukaima: Princesses no Rondo - Yuuwaku no Sunahama
659. 07-Ghost
660. Aa! Megami-sama!
661. Afro Samurai
662. Allison to Lillia
663. Denpa Onna to Seishun Otoko Special
664. Grappler Baki (TV)
665. Kaichou wa Maid-sama!: Goshujinsama to Asonjao♥
666. Kimi ga Nozomu Eien
667. Kiniro Mosaic
668. Minami-ke Okawari
669. Myself; Yourself
670. Petshop of Horrors
671. Tenchi Muyou! Ryououki 3rd Season
672. Canaan
673. Mahoutsukai ni Taisetsu na Koto: Natsu no Sora
674. Mondaiji-tachi ga Isekai kara Kuru Sou Desu yo?: Onsen Manyuuki
675. Natsu no Arashi!
676. Nazo no Kanojo X
677. Seitokai no Ichizon Lv.2: Watasu Seitokai
678. Sekirei
679. Sekirei: Pure Engagement - Kanwa ni Dai
680. Tetsuwan Birdy Decode: The Cipher
681. Vampire Knight
682. Witchblade